image: "node:latest"

cache:
  paths:
  - node_modules/

stages:
  - build
  - analysis
  - test

build:
  stage: build
  script:
    - "npm update"

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://cdelivery.fh-stralsund.de
    SONAR_ANALYSIS_MODE: issues
  script:
  - gitlab-sonar-scanner

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://cdelivery.fh-stralsund.de
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner
  
test_mocha:
  stage: test
  script:
    - "npm test"