image: "node:latest"

stages:
  - build
  - execute
  - analysis
  - test

build:
  stage: build
  script:
    - "npm install"
  artifacts:
    paths:
     - node_modules/

execute:
  stage: execute
  script: 
    - "node ./bin/www"

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://cdelivery.fh-stralsund.de
    SONAR_ANALYSIS_MODE: issues
  script:
  - gitlab-sonar-scanner

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://cdelivery.fh-stralsund.de
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner
  
test_mocha: 
  script:
    - "npm test"
    stage: test