image: "node:latest"

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - analysis
  - deploy

build:
  stage: build
  script:
    - "npm install"

test_mocha:
  stage: test
  script:
    - "npm install mocha"
    - "npm test"

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "https://cdelivery.fh-stralsund.de"
    SONAR_ANALYSIS_MODE: issues
  script:
  - gitlab-sonar-scanner -X

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "https://cdelivery.fh-stralsund.de"
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner -X

deploy_production:
  stage: deploy
  only: 
    - master
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$DEPLOYMENT_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - apt-get update -y && apt-get install -y ssh
  script:
    - ssh -p${DEPLOYMENT_SERVER_PORT} ${DEPLOYMENT_SERVER_USER}:${DEPLOYMENT_SERVER_PORT}@${DEPLOYMENT_SERVER_IP} "cd prod && docker stop docker-mainline && docker rm docker-mainline && docker build -t mainline . && docker run -p 80:3000 --name='docker-mainline' mainline"